version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-stock
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: StockProgram
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
