spring:
  hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
    show_sql: true
    hbm2ddl.auto: update

  datasource:
    url: jdbc:mysql://localhost:3310/StockProgram?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 40

  jpa:
    hibernate:
      ddl-auto: create


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
